### ISSUE TITLE
error: missing key 'data' for model '_cortex_default' 

### ISSUE THREAD

**Issue by lminer** [cortexlabs/cortex#1736]
### Version
 0.25.0

### Description

I'm trying to run a simple local server to test out cortex. I've gotten the server to build, but now it dies whenever I try to hit the api.

The code  is as follows:
```python
# client
import json
import requests

import numpy as np
wav = # numpy array of shape [50000, 2]
headers = {"content-type": "application/json"}
data = json.dumps({"audio": wav.tolist()})

json_response = requests.post(f'http://localhost:8889', data=data, headers=headers)

# server
import numpy as np
import tensorflow as tf


class TensorFlowPredictor:
    def __init__(self, tensorflow_client, config):
        self.client = tensorflow_client
        self.config = config

    def predict(self, payload, query_params, headers):
        audio = np.array(payload["audio"]).astype("float32")
        target, residual = self.client.predict(tf.convert_to_tensor(audio))
        return {"target": target.numpy().tolist(), "residual": residual.numpy().tolist()}
```

Leads to following error in the logs:
```
/opt/conda/envs/env/lib/python3.6/site-packages/cortex_internal/lib/model/tfs.py:363: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if input_name not in model_input:
2020-12-24 00:14:44.504165:cortex:pid-2248:INFO:500 Internal Server Error POST /
2020-12-24 00:14:44.504806:cortex:pid-2248:ERROR:Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/envs/env/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line
390, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/fastapi/applications.py", line 181, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/cortex_internal/serve/serve.py", line 187, in parse_payload
    return await call_next(request)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/cortex_internal/serve/serve.py", line 134, in register_request
    response = await call_next(request)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/fastapi/routing.py", line 183, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/opt/conda/envs/env/lib/python3.6/site-packages/fastapi/routing.py", line 135, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/opt/conda/envs/env/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/cortex_internal/serve/serve.py", line 200, in predict
    prediction = predictor_impl.predict(**kwargs)
  File "/mnt/project/serving/cortex_server.py", line 15, in predict
    target, residual = self.client.predict(audio)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/cortex_internal/lib/client/tensorflow.py", line
114, in predict
    return self._run_inference(model_input, consts.SINGLE_MODEL_NAME, model_version)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/cortex_internal/lib/client/tensorflow.py", line
164, in _run_inference
    return self._client.predict(model_input, model_name, model_version)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/cortex_internal/lib/model/tfs.py", line 366, in
predict
    input_name, model_name, model_version
cortex_internal.lib.exceptions.UserException: error: missing key 'data' for model '_cortex_default' of version '1608762213'
```

Here's my cortex.yaml

```yaml
- name: foo
  kind: RealtimeAPI
  predictor:
    type: tensorflow
    path: serving/cortex_server.py
    models:
      path: ../my_model/
      signature_key: serving_default
    image: quay.io/cortexlabs/python-predictor-gpu-slim:0.25.0-cuda11.0-cudnn8
    tensorflow_serving_image: quay.io/cortexlabs/tensorflow-serving-gpu:0.25.0
  compute:
    gpu: 1
```

**Comment by deliahu** [comment]
Adding @RobertLucian who will know for sure, but but based on looking at the code, my best guess is that the structure of the input that's being passed in is not matching the input signature of your model. Perhaps try something like this would work:

```python
target, residual = self.client.predict({"data": tf.convert_to_tensor(audio)})
```

Also (unrelated), you might not need to pass in a tensor, as the TensorFlow predictor can populate the tensor_proto directly from the numpy array, so maybe something like this:

```python
target, residual = self.client.predict({"data": audio})
```

**Comment by lminer** [comment]
Thanks that worked

**Comment by RobertLucian** [comment]
@lminer with regards to the error message when the inputs don't match, we've improved it here #1742. Thank you for reporting this!
