### ISSUE TITLE
Package Cortex library into .ZIP

### ISSUE THREAD

**Issue by imagine3D-ai** [cortexlabs/cortex#1781]
I'm trying to create a microservice to manage my cluster via Cortex and Lambda. AWS Lambda requires python dependencies to be packaged and uploaded as a `.zip` files. How can I package Cortex library to `.zip`?

**Comment by deliahu** [comment]
@imagine3D-ai It should work like any other pip package; here is some documentation from AWS, let us know if you aren't able to get cortex working (but are able to get other packages working, like `requests` in their example).

https://docs.aws.amazon.com/lambda/latest/dg/python-package.html#python-package-dependencies

**Comment by imagine3D-ai** [comment]
@deliahu After packaging and uploading Cortex to Lambda, I receive this error in Lambda when trying to run my code:

```
START RequestId: 47574c0d-b571-4da8-8f68-c43935eb9316 Version: $LATEST
[ERROR] CortexBinaryException: error: unable to write to home directory: /home/sbx_user1051/.cortex: mkdir /home/sbx_user1051: read-only file system

Traceback (most recent call last):
  File "/var/lang/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/lambda_function.py", line 54, in <module>
    run_cli(cli_args, hide_output=True)
  File "/var/task/cortex/binary/__init__.py", line 110, in run_cli
    raise CortexBinaryException(process.stderr.read())END RequestId: 47574c0d-b571-4da8-8f68-c43935eb9316
REPORT RequestId: 47574c0d-b571-4da8-8f68-c43935eb9316	Duration: 3639.67 ms	Billed Duration: 3640 ms	Memory Size: 128 MB	Max Memory Used: 28 MB	
Unknown application error occurred
```

After searching a bit online, it seems that Lambda allows to write only to the `/tmp` directory and Cortex is trying to write something to `/home/` and therefore I'm getting this error.

Is this something that can be fixed or should I consider other platforms like Heroku or Beanstalk to manage my Cortex cluster for now?

**Comment by imagine3D-ai** [comment]
@deliahu I'm just trying to implement some sort of interface/microservice to create and delete APIs in Cortex cluster.

**Comment by imagine3D-ai** [comment]
@deliahu My `lambda_function.py` looks like this:

```
import cortex
from cortex.binary import run_cli
import json


class PythonPredictor:
    def __init__(self, config):
        import boto3
        s3 = boto3.client('s3', aws_access_key_id='@',
        aws_secret_access_key='@')
        s3.download_file('bucket', 'config['model'], '@')
    

   def predict(self, payload):
        do something


env_name = "env"
provider = "aws"
operator_endpoint = "@"
aws_access_key_id = "@"
aws_secret_access_key = "@"

cli_args = ["env", "configure", env_name,  "--provider", provider, "--operator-endpoint", operator_endpoint, "--aws-access-key-id", aws_access_key_id, "--aws-secret-access-key", aws_secret_access_key]

run_cli(cli_args, hide_output=True)

client = cortex.client(env_name)



def lambda_handler(event, context):
    client.create_api(api_spec={
	  'name': event['api_name'],
	  'kind':'RealtimeAPI',
	  'predictor': {
	      'type': 'python',
	      'config': {'modelname': event['model']},
	  },
	  'compute': {
	    'cpu': '1',
	    'mem': '5G'
	  }}, predictor=PythonPredictor, requirements=['sse-starlette'])
    return {
        'statusCode': 200,
        'body': json.dumps(event['api_name'])
    }

```

**Comment by deliahu** [comment]
@imagine3D-ai Yes, it is possible to change the default directory that the Cortex client uses to save its configuration. Try exporting the `CORTEX_CLI_CONFIG_DIR` environment variable before running any of the client commands, e.g. `os.environ["CORTEX_CLI_CONFIG_DIR"] = "/tmp/.cortex"`. Let me know if that works!

**Comment by imagine3D-ai** [comment]
@deliahu I'm still getting `OSError`, after changing `CORTEX_CLI_CONFIG_DIR` variable:

```
import cortex
from cortex.binary import run_cli
import json
import os

os.environ["CORTEX_CLI_CONFIG_DIR"] = "/tmp/.cortex"


class PythonPredictor:
    def __init__(self, config):
        import boto3
        s3 = boto3.client('s3', aws_access_key_id='@',
        aws_secret_access_key='@')
        s3.download_file('bucket', 'config['model'], '@')
    

   def predict(self, payload):
        do something


env_name = "env"
provider = "aws"
operator_endpoint = "@"
aws_access_key_id = "@"
aws_secret_access_key = "@"

cli_args = ["env", "configure", env_name,  "--provider", provider, "--operator-endpoint", operator_endpoint, "--aws-access-key-id", aws_access_key_id, "--aws-secret-access-key", aws_secret_access_key]

run_cli(cli_args, hide_output=True)

client = cortex.client(env_name)



def lambda_handler(event, context):
    os.environ["CORTEX_CLI_CONFIG_DIR"] = "/tmp/.cortex"
    client.create_api(api_spec={
	  'name': event['api_name'],
	  'kind':'RealtimeAPI',
	  'predictor': {
	      'type': 'python',
	      'config': {'modelname': event['model']},
	  },
	  'compute': {
	    'cpu': '1',
	    'mem': '5G'
	  }}, predictor=PythonPredictor, requirements=['sse-starlette'])
    return {
        'statusCode': 200,
        'body': json.dumps(event['api_name'])
    }

```

Error message that I get:

```
{
  "errorMessage": "[Errno 30] Read-only file system: '/home/sbx_user1051'",
  "errorType": "OSError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 65, in lambda_handler\n    client.create_api(api_spec={\n",
    "  File \"/var/task/cortex/client.py\", line 99, in create_api\n    project_dir.mkdir(parents=True)\n",
    "  File \"/var/lang/lib/python3.8/pathlib.py\", line 1291, in mkdir\n    self.parent.mkdir(parents=True, exist_ok=True)\n",
    "  File \"/var/lang/lib/python3.8/pathlib.py\", line 1291, in mkdir\n    self.parent.mkdir(parents=True, exist_ok=True)\n",
    "  File \"/var/lang/lib/python3.8/pathlib.py\", line 1291, in mkdir\n    self.parent.mkdir(parents=True, exist_ok=True)\n",
    "  File \"/var/lang/lib/python3.8/pathlib.py\", line 1287, in mkdir\n    self._accessor.mkdir(self, mode)\n"
  ]
}
```

It seems to have something to do with `clent.create_api()`. Is there a way to fix this?

**Comment by deliahu** [comment]
@imagine3D-ai Thanks for following up, this is a spot in code where we did not check for the `$CORTEX_CLI_CONFIG_DIR` environment variable! (I just did a full search of our codebase to confirm there are no others)

We will get a fix out for this by end-of-day Tuesday. Is that soon enough for you, or would you like us to investigate a workaround that you could use before then? The easiest workaround would probably be for us to build you a custom version of the Python client that you could `pip install` directly from our S3 bucket.

**Comment by mutal** [comment]
@deliahu Thanks! It would be great to get a workaround before Tuesday, so that I could continue experimenting with Cortex + Lambda in the meanwhile, so please share the custom version of Python client if you could

**Comment by imagine3D-ai** [comment]
@deliahu Thanks! It would be great to get workaround before Tuesday, so that I could continue experimenting with Cortex + Lambda in the meanwhile, so please share the custom version of Python client if you could

**Comment by deliahu** [comment]
@imagine3D-ai We have implemented the fix in https://github.com/cortexlabs/cortex/pull/1798, which will be released in v0.27 (likely by tomorrow night).

In the meantime, I have built a new version of the v0.26 python client [here](https://github.com/cortexlabs/cortex/files/5833908/cortex-0.26.0.tar.gz). You can install it by running `pip install https://github.com/cortexlabs/cortex/files/5833908/cortex-0.26.0.tar.gz`.

Thanks again for bringing this up, and let us know if that fixes it!

**Comment by imagine3D-ai** [comment]
@deliahu Thanks for the client! I was able to connect to my cluster and create an api using your python client. However, the API instance didn't really go live and was stuck in the `error` state. After running `cortex logs`, I got:

```
File "/opt/conda/envs/env/lib/python3.8/site-packages/cortex_internal/lib/api/predictor.py", line 271, in _get_class_impl
    return dill.load(pickle_file)
  File "/opt/conda/envs/env/lib/python3.8/site-packages/dill/_dill.py", line 270, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/opt/conda/envs/env/lib/python3.8/site-packages/dill/_dill.py", line 473, in load
    obj = StockUnpickler.load(self)
  File "/opt/conda/envs/env/lib/python3.8/site-packages/dill/_dill.py", line 463, in find_class
    return StockUnpickler.find_class(self, module, name)
ModuleNotFoundError: No module named 'lambda_function'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/env/lib/python3.8/site-packages/cortex_internal/serve/serve.py", line 311, in start_fn
    predictor_impl = api.predictor.initialize_impl(project_dir, client)
  File "/opt/conda/envs/env/lib/python3.8/site-packages/cortex_internal/lib/api/predictor.py", line 182, in initialize_impl
    class_impl = self.class_impl(project_dir)
  File "/opt/conda/envs/env/lib/python3.8/site-packages/cortex_internal/lib/api/predictor.py", line 251, in class_impl
    predictor_class = self._get_class_impl(
  File "/opt/conda/envs/env/lib/python3.8/site-packages/cortex_internal/lib/api/predictor.py", line 273, in _get_class_impl
    raise UserException("unable to load pickle", str(e)) from e
cortex_internal.lib.exceptions.UserException: error: error in predictor.pickle: unable to load pickle: No module named 'lambda_function'
```

I define my Predictor class in the `lamda_function.py` (which runs on the Lambda platform) , like I showed in the earlier comments and `lambda_handler()` then instantiates Cortex Predictor class on Lambda API call. I'm not sure what to make of this error message that I've got.

**Comment by deliahu** [comment]
@imagine3D-ai is the `lambda_function` package used or imported anywhere in your code? My guess is that it's not, but I just wanted to confirm

**Comment by deliahu** [comment]
@imagine3D-ai One thing that is worth a try: could you try moving your class definition to be inside `lambda_handler()`, e.g.

```python
import cortex
from cortex.binary import run_cli
import json
import os

os.environ["CORTEX_CLI_CONFIG_DIR"] = "/tmp/.cortex"

env_name = "env"
provider = "aws"
operator_endpoint = "@"
aws_access_key_id = "@"
aws_secret_access_key = "@"

cli_args = ["env", "configure", env_name,  "--provider", provider, "--operator-endpoint", operator_endpoint, "--aws-access-key-id", aws_access_key_id, "--aws-secret-access-key", aws_secret_access_key]

run_cli(cli_args, hide_output=True)

client = cortex.client(env_name)


def lambda_handler(event, context):
    class PythonPredictor:
        def __init__(self, config):
            import boto3
            s3 = boto3.client('s3', aws_access_key_id='@',
            aws_secret_access_key='@')
            s3.download_file('bucket', 'config['model'], '@')
        
    
       def predict(self, payload):
            do something


    os.environ["CORTEX_CLI_CONFIG_DIR"] = "/tmp/.cortex"
    client.create_api(api_spec={
	  'name': event['api_name'],
	  'kind':'RealtimeAPI',
	  'predictor': {
	      'type': 'python',
	      'config': {'modelname': event['model']},
	  },
	  'compute': {
	    'cpu': '1',
	    'mem': '5G'
	  }}, predictor=PythonPredictor, requirements=['sse-starlette'])
    return {
        'statusCode': 200,
        'body': json.dumps(event['api_name'])
    }
```

**Comment by imagine3D-ai** [comment]
@deliahu After moving my class definition into `lambda_handler()`, `"PicklingError"` occurs:

```
{
  "errorMessage": "Can't pickle <class 'lambda_function.lambda_handler.<locals>.PythonPredictor'>: it's not found as lambda_function.lambda_handler.<locals>.PythonPredictor",
  "errorType": "PicklingError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 66, in lambda_handler\n    client.create_api(api_spec={\n",
    "  File \"/var/task/cortex/client.py\", line 141, in create_api\n    dill.dump(predictor, pickle_file)\n",
    "  File \"/var/task/dill/_dill.py\", line 259, in dump\n    Pickler(file, protocol, **_kwds).dump(obj)\n",
    "  File \"/var/task/dill/_dill.py\", line 446, in dump\n    StockPickler.dump(self, obj)\n",
    "  File \"/var/lang/lib/python3.8/pickle.py\", line 485, in dump\n    self.save(obj)\n",
    "  File \"/var/lang/lib/python3.8/pickle.py\", line 558, in save\n    f(self, obj)  # Call unbound method with explicit self\n",
    "  File \"/var/task/dill/_dill.py\", line 1381, in save_type\n    StockPickler.save_global(pickler, obj, name=name)\n",
    "  File \"/var/lang/lib/python3.8/pickle.py\", line 1068, in save_global\n    raise PicklingError(\n"
  ]
}
```

**Comment by deliahu** [comment]
@imagine3D-ai In that case, it must be some issue with how we pickle the class, or how lambda is set up. We'll investigate this and keep you posted.

In the meantime, I would recommend deploying an API using the files-based approach, as this is more battle tested, and recommended for production environments. You can still use the Python client to deploy your API, you would just move your PythonPredictor implementation into its own file. You would still use [create_api()](https://docs.cortex.dev/clients/python#create_api) and you can still pass in `api_spec`, but you would use the `project_dir` argument instead of `predictor` (you may also need to make a `requirements.txt` file with `sse-starlette` instead of passing it in through the `requirements` parameter). Here is an example of what that would look like: https://docs.cortex.dev/workloads/managing-dependencies/example

**Comment by imagine3D-ai** [comment]
> dependencies

Could the files-based approach be implemented in lambda?

**Comment by deliahu** [comment]
@imagine3D-ai I was able to get it working with the files-based approach like this:

```bash
# first, create a lambda named "test" using the aws console. I used the default python version (3.8)
# then, using the aws console, add environment variables for `CORTEX_AWS_ACCESS_KEY_ID` and `CORTEX_AWS_SECRET_ACCESS_KEY`

mkdir my-function && cd my-function
pip3 install --target ./package cortex==0.27.0
cd package/ && zip -r ../my-deployment-package.zip . && cd ..
touch lambda_function.py
mkdir name-generator && touch name-generator/predictor.py name-generator/requirements.txt
chmod 755 lambda_function.py name-generator name-generator/*  # I was getting a permissions error without this

# edit lambda_function.py, name-generator/predictor.py, and name-generator/requirements.txt (see below)

zip -g my-deployment-package.zip lambda_function.py name-generator name-generator/*  # I needed to add name-generator separately from name-generator/* to get the permissions to pass through
aws lambda update-function-code --function-name test --zip-file fileb://my-deployment-package.zip

# click the "test" button in the aws console
```

```python
# lambda_function.py

import os
import shutil
import json
import cortex

os.environ["CORTEX_CLI_CONFIG_DIR"] = "/tmp/.cortex"
shutil.copytree("./name-generator", "/tmp/name-generator")  # I had to do this because cortex writes a temporary file to the project directory

client = cortex.cluster_client(
    name="aws",
    provider="aws",
    operator_endpoint="https://a9860a09b9eb949878c792254407d50c-c1a271a86dff290c.elb.us-west-2.amazonaws.com",
    aws_access_key_id=os.getenv("CORTEX_AWS_ACCESS_KEY_ID"),
    aws_secret_access_key=os.getenv("CORTEX_AWS_SECRET_ACCESS_KEY"),
)

api_spec = {
    "name": "name-generator",
    "kind": "RealtimeAPI",
    "predictor": {
        "type": "python",
        "path": "predictor.py",
        "config": {"num_names": 2},
    },
}


def lambda_handler(event, context):
    response = client.create_api(
        api_spec=api_spec,
        project_dir="/tmp/name-generator",
    )

    return {"statusCode": 200, "body": response}
```

```python
# name-generator/requirements.txt

names
```

```python
# name-generator/predictor.py

import names

class PythonPredictor:
    def __init__(self, config):
        self.config = config

    def predict(self, payload):
        gender = payload.get("gender")
        return [names.get_full_name(gender=gender) for i in range(self.config["num_names"])]
```

```bash
# test it out

curl -H "Content-Type: application/json" -d '{"gender":"male"}' http://a6168860e23fd434aaf54bad400725a3-aca70c6f2439b1cb.elb.us-west-2.amazonaws.com/name-generator
```

Let us know if that works for you!

**Comment by deliahu** [comment]
Also, I created https://github.com/cortexlabs/cortex/issues/1824 to track the issue with unpickling the Predictor class. @vishalbollu has made some progress in investigating this, so we should have the fix merged before our next release.

**Comment by deliahu** [comment]
@imagine3D-ai I have found another workaround until we fix https://github.com/cortexlabs/cortex/issues/1824; feel free to go with whichever approach you think is cleaner:

```bash
# first, create a lambda named "test" using the aws console. I used the default python version (3.8)
# then, using the aws console, add environment variables for `CORTEX_AWS_ACCESS_KEY_ID` and `CORTEX_AWS_SECRET_ACCESS_KEY`

mkdir my-function && cd my-function
pip3 install --target ./package cortex==0.27.0
cd package/ && zip -r ../my-deployment-package.zip . && cd ..
touch lambda_function.py
chmod 755 lambda_function.py # I was getting a permissions error without this

# edit lambda_function.py (see below)

zip -g my-deployment-package.zip lambda_function.py
aws lambda update-function-code --function-name test --zip-file fileb://my-deployment-package.zip

# click the "test" button in the aws console
```

```python
# lambda_function.py

import os
import json
import cortex
import dill


os.environ["CORTEX_CLI_CONFIG_DIR"] = "/tmp/.cortex"


class PythonPredictor:
    def __init__(self, config):
        self.config = config

    def predict(self, payload):
        import names

        gender = payload.get("gender")
        return [names.get_full_name(gender=gender) for i in range(self.config["num_names"])]


requirements = ["names"]

os.mkdir("/tmp/name-generator")

with open("/tmp/name-generator/predictor.py", "w") as f:
    f.write(dill.source.importable(PythonPredictor, source=True))

with open("/tmp/name-generator/requirements.txt", "w") as f:
    f.write("\n".join(requirements))


client = cortex.cluster_client(
    name="aws",
    provider="aws",
    operator_endpoint="https://a9860a09b9eb949878c792254407d50c-c1a271a86dff290c.elb.us-west-2.amazonaws.com",
    aws_access_key_id=os.getenv("CORTEX_AWS_ACCESS_KEY_ID"),
    aws_secret_access_key=os.getenv("CORTEX_AWS_SECRET_ACCESS_KEY"),
)

api_spec = {
    "name": "name-generator",
    "kind": "RealtimeAPI",
    "predictor": {
        "type": "python",
        "path": "predictor.py",
        "config": {"num_names": 2},
    },
}


def lambda_handler(event, context):
    response = client.create_api(
        api_spec=api_spec,
        project_dir="/tmp/name-generator",
    )

    return {"statusCode": 200, "body": response}
```

**Comment by imagine3D-ai** [comment]
@deliahu Thank you so much!
